CREATE TABLE nouns (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    singular VARCHAR NOT NULL,
    plural VARCHAR NOT NULL
);

CREATE TABLE verbs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    base VARCHAR NOT NULL,
    present VARCHAR NOT NULL,
    past VARCHAR NOT NULL,
    perfect VARCHAR NOT NULL,
    continuous VARCHAR NOT NULL
);

CREATE TABLE adjectives (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    word VARCHAR NOT NULL
);

CREATE TABLE adverbs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    word VARCHAR NOT NULL
);

CREATE TABLE pronouns (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    word VARCHAR NOT NULL
);

CREATE TABLE prepositions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    word VARCHAR NOT NULL
);

CREATE TABLE determiners (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    word VARCHAR NOT NULL
);


-- Rzeczowniki
INSERT INTO nouns (singular, plural) VALUES
    ('apple', 'apples'),
    ('car', 'cars'),
    ('dog', 'dogs'),
    ('cat', 'cats'),
    ('book', 'books'),
    ('chair', 'chairs'),
    ('table', 'tables'),
    ('computer', 'computers'),
    ('phone', 'phones'),
    ('shoe', 'shoes'),
    ('house', 'houses'),
    ('tree', 'trees'),
    ('flower', 'flowers'),
    ('bottle', 'bottles'),
    ('pen', 'pens'),
    ('pencil', 'pencils'),
    ('bag', 'bags'),
    ('hat', 'hats'),
    ('shirt', 'shirts'),
    ('jacket', 'jackets'),
    ('sock', 'socks'),
    ('glove', 'gloves'),
    ('watch', 'watches'),
    ('key', 'keys'),
    ('window', 'windows'),
    ('door', 'doors'),
    ('computer', 'computers'),
    ('notebook', 'notebooks'),
    ('cup', 'cups'),
    ('plate', 'plates'),
    ('spoon', 'spoons'),
    ('fork', 'forks'),
    ('knife', 'knives'),
    ('fish', 'fish'),
    ('mouse', 'mice'),
    ('tooth', 'teeth'),
    ('child', 'children'),
    ('person', 'people'),
    ('woman', 'women'),
    ('man', 'men'),
    ('foot', 'feet'),
    ('leaf', 'leaves'),
    ('box', 'boxes'),
    ('city', 'cities'),
    ('country', 'countries'),
    ('school', 'schools'),
    ('university', 'universities'),
    ('restaurant', 'restaurants'),
    ('store', 'stores'),
    ('market', 'markets'),
    ('bank', 'banks'),
    ('hospital', 'hospitals'),
    ('library', 'libraries'),
    ('church', 'churches'),
    ('mountain', 'mountains'),
    ('river', 'rivers'),
    ('lake', 'lakes'),
    ('sea', 'seas'),
    ('ocean', 'oceans'),
    ('planet', 'planets'),
    ('star', 'stars'),
    ('moon', 'moons'),
    ('sun', 'suns'),
    ('cloud', 'clouds'),
    ('rain', 'rains'),
    ('snow', 'snows'),
    ('wind', 'winds');

-- Czasowniki
INSERT INTO verbs (base, present, past, perfect, continuous) VALUES
    ('run', 'runs', 'ran', 'run', 'running'),
    ('eat', 'eats', 'ate', 'eaten', 'eating'),
    ('jump', 'jumps', 'jumped', 'jumped', 'jumping'),
    ('play', 'plays', 'played', 'played', 'playing'),
    ('write', 'writes', 'wrote', 'written', 'writing'),
    ('speak', 'speaks', 'spoke', 'spoken', 'speaking'),
    ('read', 'reads', 'read', 'read', 'reading'),
    ('sleep', 'sleeps', 'slept', 'slept', 'sleeping'),
    ('sing', 'sings', 'sang', 'sung', 'singing'),
    ('dance', 'dances', 'danced', 'danced', 'dancing'),
    ('study', 'studies', 'studied', 'studied', 'studying'),
    ('work', 'works', 'worked', 'worked', 'working'),
    ('buy', 'buys', 'bought', 'bought', 'buying'),
    ('sell', 'sells', 'sold', 'sold', 'selling'),
    ('help', 'helps', 'helped', 'helped', 'helping'),
    ('clean', 'cleans', 'cleaned', 'cleaned', 'cleaning'),
    ('cook', 'cooks', 'cooked', 'cooked', 'cooking'),
    ('drive', 'drives', 'drove', 'driven', 'driving'),
    ('ride', 'rides', 'rode', 'ridden', 'riding'),
    ('jump', 'jumps', 'jumped', 'jumped', 'jumping'),
    ('watch', 'watches', 'watched', 'watched', 'watching'),
    ('listen', 'listens', 'listened', 'listened', 'listening'),
    ('talk', 'talks', 'talked', 'talked', 'talking'),
    ('think', 'thinks', 'thought', 'thought', 'thinking'),
    ('feel', 'feels', 'felt', 'felt', 'feeling'),
    ('understand', 'understands', 'understood', 'understood', 'understanding'),
    ('believe', 'believes', 'believed', 'believed', 'believing'),
    ('teach', 'teaches', 'taught', 'taught', 'teaching'),
    ('learn', 'learns', 'learned', 'learned', 'learning'),
    ('win', 'wins', 'won', 'won', 'winning'),
    ('lose', 'loses', 'lost', 'lost', 'losing'),
    ('build', 'builds', 'built', 'built', 'building'),
    ('create', 'creates', 'created', 'created', 'creating'),
    ('destroy', 'destroys', 'destroyed', 'destroyed', 'destroying'),
    ('open', 'opens', 'opened', 'opened', 'opening'),
    ('close', 'closes', 'closed', 'closed', 'closing'),
    ('meet', 'meets', 'met', 'met', 'meeting'),
    ('know', 'knows', 'knew', 'known', 'knowing'),
    ('go', 'goes', 'went', 'gone', 'going'),
    ('come', 'comes', 'came', 'come', 'coming'),
    ('arrive', 'arrives', 'arrived', 'arrived', 'arriving'),
    ('leave', 'leaves', 'left', 'left', 'leaving'),
    ('stay', 'stays', 'stayed', 'stayed', 'staying'),
    ('exist', 'exists', 'existed', 'existed', 'existing'),
    ('talk', 'talks', 'talked', 'talked', 'talking'),
    ('take', 'takes', 'took', 'taken', 'taking'),
    ('give', 'gives', 'gave', 'given', 'giving'),
    ('send', 'sends', 'sent', 'sent', 'sending'),
    ('receive', 'receives', 'received', 'received', 'receiving'),
    ('help', 'helps', 'helped', 'helped', 'helping'),
    ('fix', 'fixes', 'fixed', 'fixed', 'fixing'),
    ('paint', 'paints', 'painted', 'painted', 'painting'),
    ('meet', 'meets', 'met', 'met', 'meeting'),
    ('borrow', 'borrows', 'borrowed', 'borrowed', 'borrowing'),
    ('lend', 'lends', 'lent', 'lent', 'lending'),
    ('hope', 'hopes', 'hoped', 'hoped', 'hoping'),
    ('belong', 'belongs', 'belonged', 'belonged', 'belonging'),
    ('arrange', 'arranges', 'arranged', 'arranged', 'arranging'),
    ('invite', 'invites', 'invited', 'invited', 'inviting'),
    ('remember', 'remembers', 'remembered', 'remembered', 'remembering'),
    ('forget', 'forgets', 'forgot', 'forgotten', 'forgetting'),
    ('imagine', 'imagines', 'imagined', 'imagined', 'imagining'),
    ('discover', 'discovers', 'discovered', 'discovered', 'discovering'),
    ('explore', 'explores', 'explored', 'explored', 'exploring'),
    ('celebrate', 'celebrates', 'celebrated', 'celebrated', 'celebrating'),
    ('enjoy', 'enjoys', 'enjoyed', 'enjoyed', 'enjoying');

-- Przymiotniki
INSERT INTO adjectives (word) VALUES
    ('red'),
    ('quick'),
    ('happy'),
    ('blue'),
    ('slow'),
    ('tall'),
    ('short'),
    ('smart'),
    ('big'),
    ('small'),
    ('beautiful'),
    ('ugly'),
    ('strong'),
    ('weak'),
    ('bright'),
    ('dark'),
    ('cold'),
    ('hot'),
    ('warm'),
    ('cool'),
    ('soft'),
    ('hard'),
    ('heavy'),
    ('light'),
    ('young'),
    ('old'),
    ('rich'),
    ('poor'),
    ('clean'),
    ('dirty'),
    ('thin'),
    ('fat'),
    ('friendly'),
    ('mean'),
    ('kind'),
    ('rude'),
    ('honest'),
    ('dishonest'),
    ('funny'),
    ('serious'),
    ('loud'),
    ('quiet'),
    ('shy'),
    ('outgoing'),
    ('lazy'),
    ('active'),
    ('creative'),
    ('boring'),
    ('dangerous'),
    ('safe'),
    ('healthy'),
    ('sick'),
    ('rich'),
    ('poor'),
    ('safe'),
    ('dangerous'),
    ('interesting'),
    ('boring'),
    ('exciting'),
    ('dull'),
    ('calm'),
    ('nervous'),
    ('brave'),
    ('scared'),
    ('noisy'),
    ('peaceful'),
    ('colorful'),
    ('monochrome'),
    ('modern'),
    ('ancient'),
    ('cheap'),
    ('expensive'),
    ('organized'),
    ('messy'),
    ('fun'),
    ('boring'),
    ('famous'),
    ('unknown'),
    ('sweet'),
    ('sour'),
    ('salty'),
    ('bitter'),
    ('spicy'),
    ('smooth'),
    ('rough');

-- Przysłówki
INSERT INTO adverbs (word) VALUES
    ('quickly'),
    ('happily'),
    ('eagerly'),
    ('slowly'),
    ('carefully'),
    ('loudly'),
    ('quietly'),
    ('easily'),
    ('beautifully'),
    ('accurately'),
    ('seriously'),
    ('naturally'),
    ('always'),
    ('never'),
    ('often'),
    ('rarely'),
    ('occasionally'),
    ('frequently'),
    ('suddenly'),
    ('generously');

-- Zaimki
INSERT INTO pronouns (word) VALUES
    ('I'),
    ('you'),
    ('he'),
    ('she'),
    ('it'),
    ('we'),
    ('they');

-- Przyimki
INSERT INTO prepositions (word) VALUES
    ('on'),
    ('under'),
    ('over'),
    ('in'),
    ('between'),
    ('above'),
    ('below'),
    ('behind'),
    ('next to'),
    ('in front of'),
    ('beside'),
    ('near'),
    ('far from'),
    ('through'),
    ('across'),
    ('around'),
    ('by'),
    ('with'),
    ('without'),
    ('during');

-- Określniki
INSERT INTO determiners (word) VALUES
    ('the'),
    ('a'),
    ('an'),
    ('this'),
    ('that'),
    ('these'),
    ('those'),
    ('my'),
    ('your'),
    ('his'),
    ('her'),
    ('its'),
    ('our'),
    ('their'),
    ('whose'),
    ('each'),
    ('every'),
    ('some'),
    ('any'),
    ('no'),
    ('another'),
    ('such'),
    ('one'),
    ('two'),
    ('few'),
    ('many'),
    ('several'),
    ('most'),
    ('all'),
    ('half'),
    ('little'),
    ('much'),
    ('more'),
    ('less'),
    ('least'),
    ('own'),
    ('other'),
    ('another'),
    ('former'),
    ('latter'),
    ('next'),
    ('previous'),
    ('last'),
    ('first'),
    ('second'),
    ('third'),
    ('each other'),
    ('every other'),
    ('no other'),
    ('any other'),
    ('all the'),
    ('both'),
    ('either'),
    ('neither'),
    ('some other'),
    ('such a'),
    ('one of'),
    ('both of'),
    ('few of'),
    ('many of'),
    ('all of'),
    ('most of'),
    ('none of'),
    ('every one of'),
    ('each one of'),
    ('a few'),
    ('a lot of'),
    ('a great deal of'),
    ('plenty of'),
    ('a couple of'),
    ('a number of'),
    ('a great number of'),
    ('any number of'),
    ('some of');
